FROM {{ cookiecutter.python_base_image }}
LABEL maintainer="{{ cookiecutter.author }}"

ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /tmp/requirements.txt
COPY ./requirements.dev.txt /tmp/requirements.dev.txt
COPY ./app /app
WORKDIR /app
EXPOSE 8000

ARG DEV=false
RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    apk add --update --no-cache postgresql-client && \
    apk add --update --no-cache --virtual .tmp-build-deps \
        build-base postgresql-dev musl-dev && \
    /py/bin/pip install -r /tmp/requirements.txt && \
    if [ $DEV = "true" ]; \
      then /py/bin/pip install -r /tmp/requirements.dev.txt ; \
    fi && \
    rm -rf /tmp && \
    apk del .tmp-build-deps && \
    adduser \
        --disabled-password \
        --no-create-home \
    {{ cookiecutter.container_user_name }} && \
    chown {{ cookiecutter.container_user_name }}:{{ cookiecutter.container_user_name }} -R /app/

ENV PATH="/py/bin:$PATH"

USER {{ cookiecutter.container_user_name }}
